// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazIYFdIXDsMf4zQf6ffx8DKT1XY0Q0lc',
    appId: '1:448931626442:web:3a79b08a96fd35c8dce333',
    messagingSenderId: '448931626442',
    projectId: 'adminproductapp',
    authDomain: 'adminproductapp.firebaseapp.com',
    storageBucket: 'adminproductapp.firebasestorage.app',
    measurementId: 'G-SECTPBQ5XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJsf_VpwOHV7wFwlBJN3ZJflDLAWxTY4',
    appId: '1:448931626442:android:e57f56fe2a33f452dce333',
    messagingSenderId: '448931626442',
    projectId: 'adminproductapp',
    storageBucket: 'adminproductapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkqmYrA4ZES7dnErq6ILuTV2r7FznXQ9Y',
    appId: '1:448931626442:ios:e54c52cb06a54975dce333',
    messagingSenderId: '448931626442',
    projectId: 'adminproductapp',
    storageBucket: 'adminproductapp.firebasestorage.app',
    iosBundleId: 'com.example.adminProductApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkqmYrA4ZES7dnErq6ILuTV2r7FznXQ9Y',
    appId: '1:448931626442:ios:e54c52cb06a54975dce333',
    messagingSenderId: '448931626442',
    projectId: 'adminproductapp',
    storageBucket: 'adminproductapp.firebasestorage.app',
    iosBundleId: 'com.example.adminProductApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDazIYFdIXDsMf4zQf6ffx8DKT1XY0Q0lc',
    appId: '1:448931626442:web:753d4a0fea3ee866dce333',
    messagingSenderId: '448931626442',
    projectId: 'adminproductapp',
    authDomain: 'adminproductapp.firebaseapp.com',
    storageBucket: 'adminproductapp.firebasestorage.app',
    measurementId: 'G-XHEBXZ74WP',
  );
}
